{
 "title": "MONA-LISA",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "Rapid View Station",
    "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> distinct(column: \"location\")\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "xat_station",
    "label": "Health States Station",
    "query": "from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop:v.timeRangeStop)\n  |> distinct(column: \"location\")\n  |> keep(columns: [\"_value\"])\n\n  "
   },
   {
    "name": "time_xat",
    "query": "time2 = uint(v: now())\n\ndata = from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_XAT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"computer_voltage\" or r[\"_field\"] == \"device_current\" or r[\"_field\"] == \"digitizer_current\" or r[\"_field\"] == \"device_voltage\" or r[\"_field\"] == \"computer_current\" or r[\"_field\"] == \"seismometer_temperature\" or r[\"_field\"] == \"telemeter_current\" or r[\"_field\"] == \"telemeter_voltage\" or r[\"_field\"] == \"vault0_humidity\" or r[\"_field\"] == \"vault0_temperature\" or r[\"_field\"] == \"saxiul\" or r[\"_field\"] == \"outside_temperature\" or r[\"_field\"] == \"loop\" or r[\"_field\"] == \"door_2\" or r[\"_field\"] == \"door_1\" or r[\"_field\"] == \"digitizer_voltage\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keep(columns: [\"_time\"])\n  |> unique(column: \"_time\")\n  \ndata\n  |> map(fn:(r) => ({ r with _value: string(v: duration(v: time2 - uint(v: r._time))) }))\n  "
   },
   {
    "name": "time_xat_disksize1",
    "query": "time2 = uint(v: now())\n\ndata = from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_DISKSIZE1\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keep(columns: [\"_time\"])\n  |> unique(column: \"_time\")\n  \ndata\n  |> map(fn:(r) => ({ r with _value: string(v: duration(v: time2 - uint(v: r._time))) }))\n  "
   },
   {
    "name": "time_xat_batteryvoltage",
    "query": "time2 = uint(v: now())\n\ndata = from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_BATTERYVOLTAGE\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keep(columns: [\"_time\"])\n  |> unique(column: \"_time\")\n  \ndata\n  |> map(fn:(r) => ({ r with _value: string(v: duration(v: time2 - uint(v: r._time))) }))\n  "
   },
   {
    "name": "time_xat_mass_position",
    "query": "time2 = uint(v: now())\n\ndata = from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_MASS_POSITION\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keep(columns: [\"_time\"])\n  |> unique(column: \"_time\")\n  \ndata\n  |> map(fn:(r) => ({ r with _value: string(v: duration(v: time2 - uint(v: r._time))) }))\n  "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>MONA-LISA</h1>\n<h3><i> Monitoring Application of Mongolian Network</i></h3></center>"
   }
  },
  {
   "title": "${station}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "repeat": "station",
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"${station}\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "State of Health: ${xat_station}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "repeat": "xat_station",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_XAT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vault0_temperature\" or r[\"_field\"] == \"vault0_humidity\" or r[\"_field\"] == \"computer_current\" or r[\"_field\"] == \"device_current\" or r[\"_field\"] == \"computer_voltage\" or r[\"_field\"] == \"device_voltage\" or r[\"_field\"] == \"digitizer_current\" or r[\"_field\"] == \"telemeter_voltage\" or r[\"_field\"] == \"telemeter_current\" or r[\"_field\"] == \"seismometer_temperature\" or r[\"_field\"] == \"saxiul\" or r[\"_field\"] == \"outside_temperature\" or r[\"_field\"] == \"loop\" or r[\"_field\"] == \"door_2\" or r[\"_field\"] == \"door_1\" or r[\"_field\"] == \"digitizer_voltage\" or r[\"_field\"] == \"vault1_humidity\" or r[\"_field\"] == \"vault1_temperature\" or r[\"_field\"] == \"vpn_current\" or r[\"_field\"] == \"vpn_voltage\" or r[\"_field\"] == \"water_presence\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keep(columns: [\"_field\",\"_value\"])\n"
    },
    {
     "query": "from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_BATTERYVOLTAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"available_disksize\" or r[\"_field\"] == \"total_disksize\" or r[\"_field\"] == \"used_disksize\" or r[\"_field\"] == \"battery_voltage\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"e_massposition\" or r[\"_field\"] == \"n_massposition\" or r[\"_field\"] == \"z_massposition\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keep(columns: [\"_field\",\"_value\"])"
    },
    {
     "query": "from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_DISKSIZE1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"available_disksize\" or r[\"_field\"] == \"total_disksize\" or r[\"_field\"] == \"used_disksize\" or r[\"_field\"] == \"battery_voltage\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"e_massposition\" or r[\"_field\"] == \"n_massposition\" or r[\"_field\"] == \"z_massposition\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keep(columns: [\"_field\",\"_value\"])"
    },
    {
     "query": "from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_MASS_POSITION\")\n  |> filter(fn: (r) => r[\"_field\"] == \"available_disksize\" or r[\"_field\"] == \"total_disksize\" or r[\"_field\"] == \"used_disksize\" or r[\"_field\"] == \"battery_voltage\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"e_massposition\" or r[\"_field\"] == \"n_massposition\" or r[\"_field\"] == \"z_massposition\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keep(columns: [\"_field\",\"_value\"])"
    }
   ]
  },
  {
   "title": "Mass Position Last data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"regexp\"\n\ntime2 = uint(v: now())\n\ndata = from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_MASS_POSITION\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keyValues(keyColumns: [\"_time\"])\n  |> toUInt()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> unique(column: \"_value\")\n\n\ndata\n  |> map(fn:(r) => ({ r with _string_value: regexp.findString(r:/.*(.?)ms/, v: string(v: duration(v: time2 - uint(v: r._value)))) }))\n"
    }
   ]
  },
  {
   "title": "Disk Size Last data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"regexp\"\n\ntime2 = uint(v: now())\n\ndata = from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_DISKSIZE1\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keyValues(keyColumns: [\"_time\"])\n  |> toUInt()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> unique(column: \"_value\")\n\n\ndata\n  |> map(fn:(r) => ({ r with _string_value: regexp.findString(r:/.*(.?)ms/, v: string(v: duration(v: time2 - uint(v: r._value)))) }))\n"
    }
   ]
  },
  {
   "title": "Battery Voltage Last data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"regexp\"\n\ntime2 = uint(v: now())\n\ndata = from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_BATTERYVOLTAGE\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keyValues(keyColumns: [\"_time\"])\n  |> toUInt()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> unique(column: \"_value\")\n\n\ndata\n  |> map(fn:(r) => ({ r with _string_value: regexp.findString(r:/.*(.?)ms/, v: string(v: duration(v: time2 - uint(v: r._value)))) }))\n"
    }
   ]
  },
  {
   "title": "XAT Last data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"regexp\"\n\ntime2 = uint(v: now())\n\ndata = from(bucket: \"health_states\")\n  |> range(start: 2021-01-01T00:00:00Z, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HEALTH_STATES_XAT\")\n  |> filter(fn: (r) => r[\"location\"] == \"${xat_station}\")\n  |> keyValues(keyColumns: [\"_time\"])\n  |> toUInt()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> unique(column: \"_value\")\n\n\ndata\n  |> map(fn:(r) => ({ r with _string_value: regexp.findString(r:/.*(.?)ms/, v: string(v: duration(v: time2 - uint(v: r._value)))) }))\n"
    }
   ]
  },
  {
   "title": "Flat Signal Probe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> mean(column: \"_value\")\n  |> keep(columns: [\"location\", \"_value\"])"
    }
   ]
  }
 ]
}