{
 "title": "SONA",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>CTBTO: SONA</h1></center>\n"
   }
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 19, "w": 8, "x": 0, "y": 2 } },
  {
   "title": "UB.SA0M..SHN",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.SA0M..SHN\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.SA0M..SHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.SA0M..SHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.SA0M..SHE",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.SA0M..SHE\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.SA1M..SHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.SA1M..SHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.SA2M..SHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.SA2M..SHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.SA3M..SHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.SA3M..SHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.SA4M..SHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.SA4M..SHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}