{
 "title": "UB-DASE",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>UB-DASE</h1></center>\n"
   }
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 15, "w": 3, "x": 0, "y": 2 } },
  {
   "title": "Synoptic",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 15, "w": 13, "x": 3, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "query": "\nfrom(bucket: \"seismic-ub\")\n  |> range(start: -2m, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: true)\n  |> map(\n        fn: (r) => ({\n            _measurement: r._measurement,\n            _field: \"no_data\",\n            _time: r._time,\n            _start: r._start,\n            _stop: r._stop,\n            _value: if exists r._value then 0 else 1,\n            location: r.location,\n        }),\n    )\n  |> yield(name: \"nodata\")"
    },
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: -2m, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.SEMM..SHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.SEMM..SHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.ALFM..SHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.ALFM..SHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.UGDM..SHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.UGDM..SHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.ARTM..SHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.ARTM..SHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.ALFM..MHZ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.ALFM..MHZ\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.ALFM..MHE",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.ALFM..MHE\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UB.ALFM..MHN",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"seismic-ub\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SEISMIC_DATA\")\n  |> filter(fn: (r) => r[\"_field\"] == \"trace\")\n  |> filter(fn: (r) => r[\"location\"] == \"UB.ALFM..MHN\")\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}